# Generated by Django 5.1.1 on 2024-09-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('pesquisadora', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=1)),
                ('idade', models.CharField(choices=[('16_25', '16 A 25 ANOS'), ('26_34', '26 A 34 ANOS'), ('35_55', '35 A 55 ANOS'), ('acima_55', 'ACIMA DE 55 ANOS')], max_length=10)),
                ('voto_espontaneo', models.CharField(blank=True, max_length=100)),
                ('voto_atual', models.CharField(choices=[('abraazinho', 'ABRAAZINHO'), ('rogerio_ribeiro', 'ROGERIO RIBEIRO'), ('nao_sabe', 'NÃO SABE')], max_length=20)),
                ('voto_dos_nomes', models.CharField(choices=[('abraazinho', 'ABRAAZINHO'), ('rogerio_ribeiro', 'ROGERIO RIBEIRO'), ('dedinho', 'DEDINHO'), ('sergio_sessim', 'SERGIO SESSIM'), ('rafael_nobre', 'RAFAEL NOBRE'), ('neca', 'NECA'), ('alessandro_calazans', 'ALESSANDRO CALAZANS'), ('nao_sabe', 'Não Sabe')], max_length=50)),
                ('avaliacao_prefeitura', models.CharField(choices=[('bom', 'BOM'), ('regular', 'REGULAR'), ('ruim', 'RUIM'), ('pessimo', 'PÉSSIMO')], max_length=10)),
            ],
        ),
    ]
