# Generated by Django 5.1.1 on 2024-09-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pesquisa_bairro_alter_pesquisa_pesquisadora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisa',
            name='voto_dos_nomes',
        ),
    ]
